<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputMaxPrice</name>
   <tag></tag>
   <elementGuidId>b57d68d4-95a8-4080-a6b1-23d1ee1f7e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-136ojw6 > div.css-1dbjc4n > div.css-1dbjc4n.r-1awozwy.r-14lw9ot.r-1l31rp8.r-sdzlij.r-rs99b7.r-18u37iz.r-18kxxzh.r-1pn2ns4.r-5njf8e.r-lrvibr.r-y3rmyz.r-136ojw6 > input.css-11aywtz.r-u68iu3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='16,000,000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c3b8ff9-bf43-4396-abf8-a5441bead5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16,000,000</value>
      <webElementGuid>8a136766-3f1a-40c7-af8a-bfc67fddbbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>88561ef6-9e1c-4448-9bb3-581ee1a257ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>658d0ab4-2ae1-4982-ae23-610613569f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>01446da4-575e-4bf9-91f5-b0c31043bb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b1f08c71-2f2f-4dfd-b920-676361f80717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6186bfa4-fbe7-4469-9930-a9e5385e154b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>b5a7e7d2-4e91-49c3-b5f5-a4e51eff426a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-11aywtz r-u68iu3</value>
      <webElementGuid>b8540ec2-c2db-4ea3-ac17-f003c98f6dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>tvat-priceUpperBound</value>
      <webElementGuid>3e1a9400-524e-4092-89e2-b5c10aaf313f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12d2d1ae-48d2-4ff2-9bb9-1807d58dd711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-mabd2g r-1q2s4rl&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-ryqm5k&quot;]/div[@class=&quot;css-1dbjc4n r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-qklmqi&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-1udh08x r-14qw7yl&quot;]/div[@class=&quot;css-1dbjc4n r-nsbfu8 r-wk8lta r-14qw7yl r-axxi2z&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1wtj0ep r-6gpygo&quot;]/div[@class=&quot;css-1dbjc4n r-136ojw6&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-14lw9ot r-1l31rp8 r-sdzlij r-rs99b7 r-18u37iz r-18kxxzh r-1pn2ns4 r-5njf8e r-lrvibr r-y3rmyz r-136ojw6&quot;]/input[@class=&quot;css-11aywtz r-u68iu3&quot;]</value>
      <webElementGuid>6408bbab-64a9-4541-bc76-c8ed2434cae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='16,000,000']</value>
      <webElementGuid>5db53205-a2c7-4cfc-b0b7-df977e918cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div[3]/div/div/div[5]/div[4]/div/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>a39fdf70-305d-4632-8abb-38f357bb1e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9c49f519-e1f5-4699-88e7-e0a8ebe76b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
