<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TitleCitySearchResult</name>
   <tag></tag>
   <elementGuidId>f87fb5f2-f039-4efc-a5ca-56f33e2d5572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.css-4rbku5.css-901oao.r-1sixt3s.r-adyw6z.r-b88u0q.r-135wba7.r-fdjqy7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@data-testid=&quot;tvat-searchResultTitle&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8d8736f4-7bcf-450d-9e61-34131f7da98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bf5c9c94-1b38-476a-846f-a2ad0ba9df08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>999044fc-3abc-47e3-834c-811617bef7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>36d3e996-c468-48c1-8d4d-3fb26d04f7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-1sixt3s r-adyw6z r-b88u0q r-135wba7 r-fdjqy7</value>
      <webElementGuid>011836f1-5368-449b-b20f-5a3a5bf6577b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>tvat-searchResultTitle</value>
      <webElementGuid>0c605d4b-8969-4a68-9e35-b206a553ed6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your search results in Palembang, Indonesia</value>
      <webElementGuid>991e25ca-5b01-4581-a5fb-f1de84c95210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-mabd2g r-1q2s4rl&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n r-11c0sde r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-13awgt0 r-18u37iz r-1wtj0ep&quot;]/div[@class=&quot;css-1dbjc4n r-eqz5dr&quot;]/h2[@class=&quot;css-4rbku5 css-901oao r-1sixt3s r-adyw6z r-b88u0q r-135wba7 r-fdjqy7&quot;]</value>
      <webElementGuid>5abb0541-7065-4e5a-b9cf-25f908f8c07b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div/div/div/h2</value>
      <webElementGuid>4e8374e7-8b94-4a3a-aa00-fe75f4611168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Maximum price can', &quot;'&quot;, 't be less than IDR 50,000')])[1]/following::h2[1]</value>
      <webElementGuid>34431a6e-cbc3-4664-a77c-233aa039ee4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel Add-ons'])[1]/following::h2[1]</value>
      <webElementGuid>3de83ff8-4227-45c7-9f78-6f96c9f45a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHANGE'])[1]/preceding::h2[1]</value>
      <webElementGuid>3d19f543-c262-4ed4-8caa-d77706cdefd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View map'])[1]/preceding::h2[1]</value>
      <webElementGuid>ce13ee19-187f-4bcc-9e6f-09f7fcf3ddf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your search results in Palembang, Indonesia']/parent::*</value>
      <webElementGuid>b575f0b7-0c9a-4792-9dd3-1f8867a065bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>e98e7dd1-8638-44be-a404-0851921aa591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Your search results in Palembang, Indonesia' or . = 'Your search results in Palembang, Indonesia')]</value>
      <webElementGuid>6a137c58-2eee-4439-8d17-77867b0051f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
