<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WifiRadioButton</name>
   <tag></tag>
   <elementGuidId>fb9802ba-41c4-4061-9c46-44156dca26a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid=&quot;tvat-facilityFilter-WIFI&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[5]/div[1]/div[3]/div[1]/div/div[5]/div[6]/div/div[2]/div/div/div[1]/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid=&quot;tvat-facilityFilter-WIFI&quot;]</value>
      <webElementGuid>1fae5595-ffbf-4a69-b80e-4c92547d0ef3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
