<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateNewCollectionButton</name>
   <tag></tag>
   <elementGuidId>c8015360-5e87-4712-829d-e6f9c7b17cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.css-4rbku5.css-901oao.r-jwli3a.r-1sixt3s.r-ubezar.r-b88u0q.r-rjixqe.r-1wzrnnt.r-fdjqy7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[4]/div/div/div[2]/div/div/div/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>83d7bebc-5287-4947-8517-21f812b0f0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d310d587-00b7-4e03-a37c-343bc1c630f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a5d80112-79d1-46a2-bee0-935ff6a40ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>b7a0248d-4b01-42e2-b063-fe64005993aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-jwli3a r-1sixt3s r-ubezar r-b88u0q r-rjixqe r-1wzrnnt r-fdjqy7</value>
      <webElementGuid>3382088a-6f18-4ddd-9583-5078973bce39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Collection</value>
      <webElementGuid>15620283-97fb-4490-9f2f-ccfcf852a579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1awozwy r-1ihkh82&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-zd98yo r-1jgb5lz r-2o02ov r-dg7iqi r-nib5yn&quot;]/div[@class=&quot;css-1dbjc4n r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-y285pg&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-13awgt0 r-1otgn73 r-1i6wzkk r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-edyy15&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-da5iq2 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-1pi2tsx r-1777fci r-u8s1d r-13qz1uu&quot;]/h3[@class=&quot;css-4rbku5 css-901oao r-jwli3a r-1sixt3s r-ubezar r-b88u0q r-rjixqe r-1wzrnnt r-fdjqy7&quot;]</value>
      <webElementGuid>5ed5a92e-75f7-48c0-9569-6ba565a54e5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div/div[2]/div/div/div/div/div/h3</value>
      <webElementGuid>b5f9cbf7-1059-4fed-9249-03fede23a1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The easy way to organize the items you love'])[1]/following::h3[1]</value>
      <webElementGuid>e6dc6785-8b22-4961-bc4d-cf5bd06b9683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collections'])[1]/following::h3[1]</value>
      <webElementGuid>4dcbfb72-1d96-4e1e-8302-e6f7a51e8471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organize your saved items!'])[1]/preceding::h3[1]</value>
      <webElementGuid>0d965f84-4094-4565-9240-a43da30ef3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved List'])[1]/preceding::h3[2]</value>
      <webElementGuid>b4b5d138-1357-44bc-b29a-810f498c66db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create New Collection']/parent::*</value>
      <webElementGuid>40d39d45-edf0-437c-b76b-3b5f8e517c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>af5ab7b2-1e1f-4f8d-9dcf-75355e16ba20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Create New Collection' or . = 'Create New Collection')]</value>
      <webElementGuid>666bcd8e-a7ca-48b5-89dc-ffa80c23d33b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
