<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HotelCardBestonHotelPalembang</name>
   <tag></tag>
   <elementGuidId>b3ed8c8f-65e1-47e2-a54b-5da6a3db48ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[3]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>ae043b79-f1b7-4503-9c0e-0cf5879a27f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>faf91572-ce58-427b-b99a-c87f3b38c009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b564deb7-054e-44b0-938b-e57b1fa55aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>b5957cd5-b7c5-4dd1-af04-48c4e70958f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-1sixt3s r-ubezar r-b88u0q r-rjixqe r-15zivkp r-fdjqy7</value>
      <webElementGuid>ca8e1e3b-a8ca-479f-bdb6-881bae993b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beston Hotel Palembang (FKA Horison Ultima Palembang)</value>
      <webElementGuid>a8d583a3-6e44-41b7-ae14-288bd196324b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1awozwy r-1ihkh82&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-zd98yo r-1jgb5lz r-2o02ov r-dg7iqi r-nib5yn&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1ul06mb&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy&quot;]/div[@class=&quot;css-1dbjc4n r-1udh08x r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-1otgn73 r-1i6wzkk r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-da5iq2 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-ymttw5 r-95jzfe&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-1ow6zhx r-88pszg&quot;]/h3[@class=&quot;css-4rbku5 css-901oao r-1sixt3s r-ubezar r-b88u0q r-rjixqe r-15zivkp r-fdjqy7&quot;]</value>
      <webElementGuid>b91c0df5-4c85-46dd-81da-c17f22fa1d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[3]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/h3</value>
      <webElementGuid>cdd67ede-b45d-446c-9dee-a4b1decbe97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotels'])[3]/following::h3[1]</value>
      <webElementGuid>82a768fb-e83a-4589-a0ae-f1865d57f21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1 guest(s), 1 room(s), 1 night(s))'])[1]/following::h3[1]</value>
      <webElementGuid>09332e9b-3c63-4fb7-9f31-8a75695b125a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thu, 23 Mar 2023'])[2]/preceding::h3[1]</value>
      <webElementGuid>07e4e414-3572-4fef-9ec7-aed1adea17d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::h3[1]</value>
      <webElementGuid>5ff33501-0cdd-41c3-af3c-55ac3d836fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beston Hotel Palembang (FKA Horison Ultima Palembang)']/parent::*</value>
      <webElementGuid>b700f774-9b6e-4d6b-af29-a8d07130f405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/h3</value>
      <webElementGuid>0f296c14-3cea-4379-8936-1b11741b8355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Beston Hotel Palembang (FKA Horison Ultima Palembang)' or . = 'Beston Hotel Palembang (FKA Horison Ultima Palembang)')]</value>
      <webElementGuid>175a64f7-9c24-47dc-a124-2000e19d002a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
