<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddButtonOnCollectionPopUp</name>
   <tag></tag>
   <elementGuidId>2a1320d8-6896-4cf5-84f0-f32107a2d0d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-1awozwy.r-1naam9t.r-sdzlij.r-1phboty.r-d045u9.r-z80fyv.r-1777fci.r-19wmn03 > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-id='IcSymbolAddPlus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>4afd2ab3-f844-4b41-ac18-2d23adc6714a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>8addf109-4b1f-46be-b73f-b7b95adcc599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>9c6d9867-0462-4a81-ba99-bab09d6e8a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>0e0c7cc8-49b5-43de-82b6-85d25cb6bb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a62495cd-4bcd-4785-a9fd-fb1926b92d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b75440f7-af65-48e3-bb15-f6d304f6874d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>IcSymbolAddPlus</value>
      <webElementGuid>6ed753f5-dde1-4f17-b927-fc89041d6a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[18]/div[@class=&quot;css-1dbjc4n r-1niwhzg r-1p0dtai r-6koalj r-1d2f490 r-1xcajam r-zchlnj r-ipm5af&quot;]/div[@class=&quot;css-1dbjc4n r-1kihuf0 r-13awgt0 r-1777fci r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-1l7z4oj&quot;]/div[@class=&quot;css-1dbjc4n r-ymttw5 r-tskmnb&quot;]/div[@class=&quot;css-1dbjc4n r-1uq9rlk r-1rnoaur&quot;]/div[@class=&quot;css-1dbjc4n r-1peese0&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-1wtj0ep&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-1otgn73 r-1i6wzkk r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-1naam9t r-sdzlij r-1phboty r-d045u9 r-z80fyv r-1777fci r-19wmn03&quot;]/svg[1]</value>
      <webElementGuid>de1f33f4-f384-46ac-8643-24e27b6326d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>9f2f72a5-40c2-44d3-ba0e-2dbcdd0a8765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>a30914de-89ec-457a-8122-51d8487eabf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
