<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TitleHotelJakartaDetailPage</name>
   <tag></tag>
   <elementGuidId>d7287dc4-c0ab-49e4-8a05-f4f5bfad58d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.css-4rbku5.css-901oao.r-1sixt3s.r-adyw6z.r-b88u0q.r-vrz42v.r-fdjqy7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[5]/div/div/div[3]/div/div/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>09092f79-d8e6-4dd1-a223-096aa1d16167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>00500cbf-8adb-4be1-9c91-a616382347ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>8742e6c2-0e16-46cd-b37d-0ee321472fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>edb12a35-e5ad-4882-889f-ec97d060e895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-1sixt3s r-adyw6z r-b88u0q r-vrz42v r-fdjqy7</value>
      <webElementGuid>6bdc05b6-40c3-454a-9812-2be5ae43f422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotel Mulia Senayan, Jakarta</value>
      <webElementGuid>6f023e4b-ce12-45d5-8fe6-f9f5fba9508e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-1r5su4o r-uwe93p r-pezta&quot;]/div[@class=&quot;css-1dbjc4n r-1oszu61 r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-b4qz5r r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-nsbfu8&quot;]/div[@class=&quot;css-1dbjc4n r-1oszu61 r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n r-1habvwh r-18u37iz r-1wtj0ep&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-15zivkp&quot;]/h1[@class=&quot;css-4rbku5 css-901oao r-1sixt3s r-adyw6z r-b88u0q r-vrz42v r-fdjqy7&quot;]</value>
      <webElementGuid>910f3aea-7343-4c22-a941-256662fb4ecf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[5]/div/div/div[3]/div/div/div/div/div/div/h1</value>
      <webElementGuid>da486a74-1803-4a1c-8132-794e87d4d1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Search'])[1]/following::h1[1]</value>
      <webElementGuid>2cbdf992-f7c3-462f-aef2-9d18c474c256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel Mulia Senayan, Jakarta'])[1]/following::h1[1]</value>
      <webElementGuid>0fd9dd21-b44f-42ea-9015-ab0cfcc1ce89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotels'])[2]/preceding::h1[1]</value>
      <webElementGuid>666e0f81-130c-42c6-9913-72243387a520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jalan Asia Afrika Senayan, Kebayoran Baru, Senayan, Jakarta, Indonesia, 10270'])[1]/preceding::h1[1]</value>
      <webElementGuid>09d74018-afd0-4877-8e7c-900dbbdb12a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7886c22a-17e3-4ee6-ab0f-dea2c630169e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Hotel Mulia Senayan, Jakarta' or . = 'Hotel Mulia Senayan, Jakarta')]</value>
      <webElementGuid>8fd61341-8eb5-40b2-abce-d4c379d438d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
