<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HotelsMenu</name>
   <tag></tag>
   <elementGuidId>055737c3-d0a8-49ed-a77c-88ee91a33889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Hotels')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-14lw9ot.r-855088.r-mm0ijv.r-dwliz8.r-1loqt21.r-6koalj.r-18u37iz.r-ymttw5.r-5njf8e.r-bnwqim.r-14qw7yl.r-1j63xyz.r-lrvibr.r-1x4r79x > div.css-901oao.r-1h9nbw7.r-16y2uox.r-1sixt3s.r-1b43r93.r-majxgm.r-1cwl3u0.r-fdjqy7.r-3s2u2q</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69184794-be71-4276-80ec-aa64aeceb39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>07d66a3f-0b78-42d8-b0e2-27812b602522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-1h9nbw7 r-16y2uox r-1sixt3s r-1b43r93 r-majxgm r-1cwl3u0 r-fdjqy7 r-3s2u2q</value>
      <webElementGuid>d92a9555-e48f-4ab9-89ce-e0e9228426cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotels</value>
      <webElementGuid>677d2389-3a40-4b54-aebe-2fdcc8d01c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-xiad99 r-16k0tzm&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-1yos0t3 r-bztko3 r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-pezta&quot;]/div[@class=&quot;css-1dbjc4n r-6koalj r-18u37iz r-12w9sp&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0 r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-u8s1d r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-1otgn73 r-1x4r79x&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-855088 r-mm0ijv r-dwliz8 r-1loqt21 r-6koalj r-18u37iz r-ymttw5 r-5njf8e r-bnwqim r-14qw7yl r-1j63xyz r-lrvibr r-1x4r79x&quot;]/div[@class=&quot;css-901oao r-1h9nbw7 r-16y2uox r-1sixt3s r-1b43r93 r-majxgm r-1cwl3u0 r-fdjqy7 r-3s2u2q&quot;]</value>
      <webElementGuid>f0126687-416c-423f-9b70-eda61e8c67a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>4e9ad4de-a819-4978-975a-574db492399f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::div[5]</value>
      <webElementGuid>fbcc9cdc-8940-4132-868d-f308a7a5d5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See more promos'])[1]/following::div[19]</value>
      <webElementGuid>12346a27-e3bf-47ce-8717-4d27bbfda35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Stays'])[1]/preceding::div[2]</value>
      <webElementGuid>8dba4d98-9c41-41e8-bb6c-af772012de28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xperience'])[1]/preceding::div[6]</value>
      <webElementGuid>c1e482a0-208b-4ec1-a6b7-b8d39b78d83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotels']/parent::*</value>
      <webElementGuid>1ec0d7d3-9f4a-465b-a383-b7d1491d74da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>a4551ade-d331-4ac8-9fa9-5f1aeda7ee58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hotels' or . = 'Hotels')]</value>
      <webElementGuid>386d3901-ed35-4dd4-a973-13cc40e2ef2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
