<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RecentlyViewedHotelsButton</name>
   <tag></tag>
   <elementGuidId>48aa81f5-2975-46a7-b2b0-70b0f8c8be3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-901oao.r-1sixt3s.r-1b43r93.r-b88u0q.r-rjixqe.r-fdjqy7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Recently Viewed Hotels')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c84a5422-3fc3-435d-a84c-13934e05ba8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>94cd77d2-5460-44b1-9675-56f290eccba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-1sixt3s r-1b43r93 r-b88u0q r-rjixqe r-fdjqy7</value>
      <webElementGuid>b24b13ba-6359-48c1-936d-156e229c7aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recently Viewed Hotels</value>
      <webElementGuid>9065897b-8b44-4e2d-aa8f-33241d88722a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-xiad99 r-16k0tzm&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-1yos0t3 r-bztko3 r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-pezta&quot;]/div[@class=&quot;css-1dbjc4n r-6koalj r-18u37iz r-12w9sp&quot;]/div[@class=&quot;css-1dbjc4n r-16y2uox r-1wbh5a2 r-zm1pxt&quot;]/div[@class=&quot;css-1dbjc4n r-1habvwh r-1ihkh82 r-o8yidv r-ir6n1k r-18u37iz r-1wtj0ep r-mvpalk&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-1otgn73 r-1i6wzkk r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-1qhn6m8 r-1f1sjgu&quot;]/div[@class=&quot;css-901oao r-1sixt3s r-1b43r93 r-b88u0q r-rjixqe r-fdjqy7&quot;]</value>
      <webElementGuid>4d3e080f-427c-422a-a3e6-6bc6e9de0039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div/div/div/div[3]/div/div/div/div[2]</value>
      <webElementGuid>b361db0d-75bc-4498-996b-d45258bba8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price Alert'])[1]/following::div[8]</value>
      <webElementGuid>19c228b6-b7d9-4251-a0e8-57aae820591c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Budget Planner'])[1]/following::div[16]</value>
      <webElementGuid>e2e54e56-cb64-4b13-8bbf-f58216e962ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City, destination, or hotel name'])[1]/preceding::div[1]</value>
      <webElementGuid>32983c29-a27a-4659-9cfe-c901246e7fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-in'])[1]/preceding::div[11]</value>
      <webElementGuid>178f7c8b-b8b2-4b1f-ac8e-00ef7c976825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recently Viewed Hotels']/parent::*</value>
      <webElementGuid>63e45dc2-20a2-405b-acd8-c809e58ba009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/div/div[2]</value>
      <webElementGuid>e1d86870-12f8-40b2-8f35-069b20f59fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Recently Viewed Hotels' or . = 'Recently Viewed Hotels')]</value>
      <webElementGuid>57370448-8118-4f1e-8bde-5d766fc14e72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
